In [1]:
!pip install -q -U transformers accelerate datasets sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 88.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 26.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 33.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 32.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 99.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

In [2]:
import numpy as np
import pandas as pd
import torch
import wandb

from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    Trainer,
    TrainingArguments,
)

In [3]:
train = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv"
)

test = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv"
)

sample_submission = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv"
)

print("Train shape:", train.shape)
print("Test shape :", test.shape)

train.head()

Train shape: (2000, 8)
Test shape : (500, 7)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

In [4]:
label2id = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

id2label = {
    v: k for k, v in label2id.items()
}

train["label"] = train["answer"].map(label2id)

In [5]:
def prepare_text(example):

    return {

        "text": (

            f"Question:\n{example['prompt']}\n\n"

            f"Options:\n"

            f"A. {example['A']}\n"

            f"B. {example['B']}\n"

            f"C. {example['C']}\n"

            f"D. {example['D']}\n"

            f"E. {example['E']}\n\n"

            "Choose the correct answer."

        )

    }

train_dataset = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [6]:
train_df, valid_df = train_test_split(
    train,
    test_size=0.10,
    stratify=train["label"],
    random_state=42
)

train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(valid_df)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
valid_dataset = valid_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [7]:
ELECTRA_MODEL = "google/electra-base-discriminator"

electra_tokenizer = AutoTokenizer.from_pretrained(
    ELECTRA_MODEL
)

electra_model = AutoModelForSequenceClassification.from_pretrained(
    ELECTRA_MODEL,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] ElectraForSequenceClassification LOAD REPORT from: google/electra-base-discriminator
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
electra.embeddings_project.weight                 | UNEXPECTED |
electra.embeddings_project.bias                   | UNEXPECTED |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.dense.weight                           | MISSING    |
classifier.out_proj.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
def electra_tokenize(example):

    return electra_tokenizer(
        example["text"],
        truncation=True,
        max_length=384
    )


electra_train = train_dataset.map(
    electra_tokenize,
    batched=True
)

electra_valid = valid_dataset.map(
    electra_tokenize,
    batched=True
)

electra_test = test_dataset.map(
    electra_tokenize,
    batched=True
)

electra_collator = DataCollatorWithPadding(
    tokenizer=electra_tokenizer
)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [9]:
def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=-1
    )

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [10]:
electra_args = TrainingArguments(

    output_dir="./electra_results",

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    weight_decay=0.01,

    warmup_steps=100,

    logging_steps=50,

    save_total_limit=1,

    fp16=torch.cuda.is_available(),

    report_to="none"
)

In [11]:
electra_trainer = Trainer(

    model=electra_model,

    args=electra_args,

    train_dataset=electra_train,

    eval_dataset=electra_valid,

    data_collator=electra_collator,

    compute_metrics=compute_metrics

)

In [12]:
electra_trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=565, training_loss=0.9662219201569009, metrics={'train_runtime': 399.3481, 'train_samples_per_second': 22.537, 'train_steps_per_second': 1.415, 'total_flos': 1714288700130528.0, 'train_loss': 0.9662219201569009, 'epoch': 5.0})

In [13]:
electra_trainer.save_model("electra_best")

electra_tokenizer.save_pretrained("electra_best")

print("Electra model saved!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Electra model saved!

In [14]:
electra_predictions = electra_trainer.predict(
    electra_test
)

electra_logits = electra_predictions.predictions

print(electra_logits.shape)

(500, 5)

In [15]:
np.save(
    "electra_logits.npy",
    electra_logits
)

print("Electra logits saved!")

Electra logits saved!

In [16]:
DISTIL_MODEL = "distilroberta-base"

distil_tokenizer = AutoTokenizer.from_pretrained(
    DISTIL_MODEL
)

distil_model = AutoModelForSequenceClassification.from_pretrained(
    DISTIL_MODEL,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: distilroberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.weight        | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [17]:
def distil_tokenize(example):

    return distil_tokenizer(
        example["text"],
        truncation=True,
        max_length=384
    )


distil_train = train_dataset.map(
    distil_tokenize,
    batched=True
)

distil_valid = valid_dataset.map(
    distil_tokenize,
    batched=True
)

distil_test = test_dataset.map(
    distil_tokenize,
    batched=True
)

distil_collator = DataCollatorWithPadding(
    tokenizer=distil_tokenizer
)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [18]:
distil_args = TrainingArguments(

    output_dir="./distil_results",

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    weight_decay=0.01,

    warmup_steps=100,

    logging_steps=50,

    save_total_limit=1,

    fp16=torch.cuda.is_available(),

    report_to="none"

)

In [19]:
distil_trainer = Trainer(

    model=distil_model,

    args=distil_args,

    train_dataset=distil_train,

    eval_dataset=distil_valid,

    data_collator=distil_collator,

    compute_metrics=compute_metrics

)

In [20]:
distil_trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=565, training_loss=0.8220280084132621, metrics={'train_runtime': 215.9658, 'train_samples_per_second': 41.673, 'train_steps_per_second': 2.616, 'total_flos': 867401534479680.0, 'train_loss': 0.8220280084132621, 'epoch': 5.0})

In [21]:
distil_trainer.save_model("distil_best")

distil_tokenizer.save_pretrained("distil_best")

print("DistilRoBERTa model saved!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

DistilRoBERTa model saved!

In [22]:
distil_predictions = distil_trainer.predict(
    distil_test
)

distil_logits = distil_predictions.predictions

print(distil_logits.shape)

(500, 5)

In [23]:
np.save(
    "distil_logits.npy",
    distil_logits
)

print("Distil logits saved!")

Distil logits saved!

In [24]:
ensemble_logits = (
    1.0 * electra_logits +
    0.0 * distil_logits
)

In [25]:
top3 = np.argsort(
    ensemble_logits,
    axis=1
)[:, -3:][:, ::-1]

predictions = [

    " ".join(
        id2label[idx]
        for idx in row
    )

    for row in top3

]

In [26]:
submission = sample_submission.copy()

submission["Prediction"] = predictions

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

   ID Prediction
0   1      A E C
1   2      B D C
2   3      B D A
3   4      E D C
4   5      C D E

In [27]:
import os

print("submission.csv exists:", os.path.exists("submission.csv"))
print(os.listdir("/kaggle/working"))

submission.csv exists: True
['__notebook__.ipynb', 'electra_logits.npy', 'distil_best', 'distil_logits.npy', 'electra_results', 'electra_best', 'distil_results', 'submission.csv']

In [1]:
!pip install -q -U transformers accelerate datasets sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 91.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 99.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

In [2]:
import numpy as np
import pandas as pd
import torch


from datasets import Dataset
from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)

import wandb

In [3]:
train = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv"
)

test = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv"
)

sample_submission = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv"
)

print("Train shape:", train.shape)
print("Test shape :", test.shape)

train.head()

Train shape: (2000, 8)
Test shape : (500, 7)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

In [4]:
label2id = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

id2label = {
    v: k for k, v in label2id.items()
}

train["label"] = train["answer"].map(label2id)

In [5]:
def prepare_text(example):
    return {
        "text": (
            f"Question:\n{example['prompt']}\n\n"
            f"Options:\n"
            f"A. {example['A']}\n"
            f"B. {example['B']}\n"
            f"C. {example['C']}\n"
            f"D. {example['D']}\n"
            f"E. {example['E']}\n\n"
            "Choose the correct answer."
        )
    }

train_dataset = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [6]:
train_df, valid_df = train_test_split(
    train,
    test_size=0.1,
    stratify=train["label"],
    random_state=42
)

train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(valid_df)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
valid_dataset = valid_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [7]:
MODEL_NAME = "YituTech/conv-bert-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/674 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/423M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/423M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/281 [00:00<?, ?it/s]

[transformers] ConvBertForSequenceClassification LOAD REPORT from: YituTech/conv-bert-base
Key                        | Status  |
---------------------------+---------+-
classifier.dense.weight    | MISSING |
classifier.out_proj.weight | MISSING |
classifier.out_proj.bias   | MISSING |
classifier.dense.bias      | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=384
    )

train_dataset = train_dataset.map(tokenize, batched=True)
valid_dataset = valid_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [9]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [10]:
training_args = TrainingArguments(

    output_dir="./results",

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    weight_decay=0.01,

    warmup_steps=100,

    logging_steps=50,

    save_total_limit=1,

    fp16=torch.cuda.is_available(),

    report_to="none"
)

In [11]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=valid_dataset,

    data_collator=data_collator,

    compute_metrics=compute_metrics
)

In [12]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

TrainOutput(global_step=565, training_loss=1.0400826219963817, metrics={'train_runtime': 441.2355, 'train_samples_per_second': 20.397, 'train_steps_per_second': 1.28, 'total_flos': 1648118751354336.0, 'train_loss': 1.0400826219963817, 'epoch': 5.0})

In [13]:
metrics = trainer.evaluate()

print(metrics)

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.011910316534340382, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1': 1.0}

In [14]:
trainer.save_model("best_model")
tokenizer.save_pretrained("best_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!
The OrderedVocab you are attempting to save contains holes for indices [1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1403, 1404, 1405, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1424, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1484, 1485, 1486

('best_model/tokenizer_config.json', 'best_model/tokenizer.json')

, 1487, 1488, 1490, 1491, 1492, 1493, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1511, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1583, 1584, 1585, 1586, 1587, 1589, 1590, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1617, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1632, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1741, 1742, 1743, 1744, 1745, 1746, 1748, 1749, 1751, 1752, 1753, 1754, 1755, 1756, 1758, 1759, 1760, 1762, 1766, 1769, 1770, 1771, 1777, 1778, 1781, 1783, 1784, 1785, 1788, 1789, 1790, 1792, 1793, 1794, 1797, 1798, 1800, 1801, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1816, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1828, 1829, 1835, 1836, 1839, 1840, 1841, 1843, 1846, 1847, 1849, 1850, 1851, 1854, 1855, 1856, 1858, 1861, 1862, 1865, 1866, 1867, 1870, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1886, 1887, 1888, 1891, 1892, 1893, 1894, 1895, 1898, 1899, 1910, 1911, 1914, 1916, 1918, 1920, 1923, 1926, 1931, 1932, 1935, 1938, 1945, 1952, 1954, 1958, 1959, 1960, 1962, 1963, 1966, 1970, 1972, 1975, 1979, 1982, 1984, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 8229, 11622, 11871, 12744, 17004, 19109, 19110, 22543, 24102, 29847, 29848, 29849, 29850, 29851, 29852, 29853, 29854, 29855, 29856, 29857, 29858, 29859, 29860, 29861, 29862, 29863, 29864, 29865, 29866, 29867, 29868, 29869, 29870, 29871, 29872, 29873, 29874, 29875, 29876, 29879, 29880, 29882, 29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891, 29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900, 29901, 29902, 29903, 29904, 29905, 29906, 29907, 29908, 29909, 29910, 29911, 29912, 29913, 29914, 29918, 29919, 29920, 29921, 29922, 29923, 29924, 29925, 29926, 29927, 29928, 29929, 29930, 29931, 29933, 29934, 29936, 29937, 29939, 29940, 29941, 29945, 29946, 29947, 29948, 29949, 29950, 29951, 29952, 29953, 29954, 29955, 29956, 29957, 29960, 29962, 29963, 29964, 29965, 29966, 29967, 29968, 29969, 29970, 29971, 29974, 29975, 29976, 29977, 29978, 29979, 29980, 29981, 29982, 29983, 29984, 29985, 29986, 29987, 29988, 29989, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 29999, 30000, 30001, 30002, 30003, 30004, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 30018, 30020, 30021, 30022, 30023, 30024, 30026, 30027, 30028, 30029, 30032, 30033, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 30041, 30042, 30043, 30044, 30046, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30068, 30070, 30071, 30072, 30073, 30074, 30075, 30076, 30077, 30078, 30079, 30081, 30082, 30083, 30084, 30085, 30086, 30087, 30088, 30089, 30090, 30091, 30092, 30093, 30094, 30095, 30096, 30097, 30098, 30099, 30100, 30101, 30102, 30103, 30105, 30106, 30107, 30109, 30111, 30112, 30113, 30114, 30115, 30117, 30118, 30120, 30121, 30122, 30123, 30124, 30125, 30126, 30127, 30128, 30129, 30130, 30131, 30133, 30134, 30135, 30137, 30138, 30139, 30144, 30147, 30148, 30150, 30151, 30152, 30153, 30155, 30158, 30161, 30162, 30163, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30172, 30173, 30174, 30175, 30176, 30177, 30178, 30179, 30180, 30181, 30182, 30183, 30184, 30185, 30186, 30187, 30188, 30189, 30190, 30191, 30192, 30193, 30194, 30195, 30196, 30197, 30198, 30199, 30200, 30201, 30202, 30203, 30206, 30207, 30208, 30209, 30210, 30211, 30212, 30213, 30214, 30215, 30216, 30217, 30218, 30219, 30220, 30221, 30222, 30223, 30224, 30225, 30226, 30227, 30228, 30229, 30230, 30231, 30232, 30233, 30234, 30236, 30237, 30238, 30239, 30240, 30241, 30242, 30243, 30244, 30245, 30246, 30247, 30248, 30249, 30250, 30251, 30252, 30253, 30254, 30255, 30256, 30257, 30258, 30259, 30260, 30261, 30262, 30263, 30264, 30267, 30268, 30269, 30270, 30271, 30272, 30274, 30275, 30277, 30278, 30279, 30280, 30281, 30282, 30284, 30285, 30286, 30288, 30292, 30295, 30296, 30297, 30303, 30304, 30307, 30309, 30310, 30311, 30314, 30315, 30316, 30318, 30319, 30320, 30323, 30324, 30326, 30327, 30331, 30334, 30335, 30336, 30337, 30338, 30340, 30342, 30345, 30346, 30347, 30348, 30349, 30350, 30351, 30354, 30355, 30361, 30362, 30365, 30366, 30367, 30369, 30372, 30373, 30375, 30376, 30377, 30380, 30381, 30382, 30384, 30387, 30388, 30391, 30392, 30393, 30396, 30398, 30399, 30400, 30401, 30403, 30404, 30405, 30412, 30413, 30414, 30417, 30418, 30419, 30420, 30421, 30424, 30425, 30436, 30437, 30440, 30442, 30444, 30446, 30449, 30452, 30457, 30458, 30461, 30464, 30471, 30478, 30480, 30484, 30485, 30486, 30488, 30489, 30492, 30496, 30498, 30501, 30505, 30508, 30510, 30512, 30513, 30514, 30515, 30516, 30517, 30518, 30519], your vocabulary could be corrupted!

In [15]:
predictions = trainer.predict(test_dataset)

logits = predictions.predictions

top3 = np.argsort(logits, axis=1)[:, -3:][:, ::-1]

preds = [
    " ".join([id2label[idx] for idx in row])
    for row in top3
]

In [16]:
submission = sample_submission.copy()

submission["Prediction"] = preds

submission.to_csv("submission.csv", index=False)

submission.head()

   ID Prediction
0   1      A D E
1   2      B D E
2   3      B D E
3   4      E C A
4   5      C E A

In [17]:
import os

print("submission.csv exists:", os.path.exists("submission.csv"))
print(os.listdir("/kaggle/working"))

submission.csv exists: True
['results', 'best_model', 'submission.csv', '__notebook__.ipynb']

In [1]:
!pip install -q -U transformers accelerate datasets sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 96.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 24.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 98.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

In [2]:
import numpy as np
import pandas as pd
import torch


from datasets import Dataset
from sklearn.model_selection import train_test_split

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)

import wandb

In [3]:
train = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv"
)

test = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv"
)

sample_submission = pd.read_csv(
    "/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv"
)

print("Train shape:", train.shape)
print("Test shape :", test.shape)

train.head()

Train shape: (2000, 8)
Test shape : (500, 7)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

In [4]:
label2id = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

id2label = {
    v: k for k, v in label2id.items()
}

train["label"] = train["answer"].map(label2id)

In [5]:
def prepare_text(example):
    return {
        "text": (
            f"Question:\n{example['prompt']}\n\n"
            f"Options:\n"
            f"A. {example['A']}\n"
            f"B. {example['B']}\n"
            f"C. {example['C']}\n"
            f"D. {example['D']}\n"
            f"E. {example['E']}\n\n"
            "Choose the correct answer."
        )
    }

train_dataset = Dataset.from_pandas(train)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [6]:
train_df, valid_df = train_test_split(
    train,
    test_size=0.1,
    stratify=train["label"],
    random_state=42
)

train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(valid_df)
test_dataset = Dataset.from_pandas(test)

train_dataset = train_dataset.map(prepare_text)
valid_dataset = valid_dataset.map(prepare_text)
test_dataset = test_dataset.map(prepare_text)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [7]:
MODEL_NAME = "xlm-roberta-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=384
    )

train_dataset = train_dataset.map(tokenize, batched=True)
valid_dataset = valid_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [9]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [10]:
training_args = TrainingArguments(

    output_dir="./results",

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    weight_decay=0.01,

    warmup_steps=100,

    logging_steps=50,

    save_total_limit=1,

    fp16=torch.cuda.is_available(),

    report_to="none"
)

In [11]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=valid_dataset,

    data_collator=data_collator,

    compute_metrics=compute_metrics
)

In [12]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=565, training_loss=1.023329360387494, metrics={'train_runtime': 511.4731, 'train_samples_per_second': 17.596, 'train_steps_per_second': 1.105, 'total_flos': 1755853144197888.0, 'train_loss': 1.023329360387494, 'epoch': 5.0})

In [13]:
metrics = trainer.evaluate()

print(metrics)

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

{'eval_loss': 0.007354610599577427, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1': 1.0}

In [14]:
trainer.save_model("best_model")
tokenizer.save_pretrained("best_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('best_model/tokenizer_config.json', 'best_model/tokenizer.json')

In [15]:
predictions = trainer.predict(test_dataset)

logits = predictions.predictions

top3 = np.argsort(logits, axis=1)[:, -3:][:, ::-1]

preds = [
    " ".join([id2label[idx] for idx in row])
    for row in top3
]

In [16]:
submission = sample_submission.copy()

submission["Prediction"] = preds

submission.to_csv("submission.csv", index=False)

submission.head()

   ID Prediction
0   1      A C D
1   2      B C D
2   3      B C D
3   4      E D A
4   5      C D B

In [17]:
import os

print("submission.csv exists:", os.path.exists("submission.csv"))
print(os.listdir("/kaggle/working"))

submission.csv exists: True
['results', '__notebook__.ipynb', 'submission.csv', 'best_model']